# conda environment description file for readthedocs build environment

name: wwatch3-cmd-rtd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.7

  # RTD packages
  - mock
  - pillow
  - sphinx
  - sphinx_rtd_theme
